// Source-of-truth exercise catalog/data (extracted from monolith)
export const EX=[
  {id:"bench",name:"Barbell Bench Press",tags:["chest","push","upper"],rest:"2-3 min",howTo:["Retract shoulder blades, arch upper back, plant feet.","Lower bar to lower chest, elbows ~45°.","Drive up explosively to lockout."],books:["Copy of OffSeason_2ndEdition_Final.pdf","IN Season workouts.pdf"],kw:["bench","press","chest"]},
  {id:"incline_db",name:"Incline DB Press",tags:["chest","push","upper"],rest:"90s",howTo:["Bench 30-45°, dumbbells at shoulders.","Press up and slightly inward.","Lower with control."],books:["Copy of OffSeason_2ndEdition_Final.pdf"],kw:["incline","dumbbell","chest"]},
  {id:"cgbench",name:"Close-Grip Bench",tags:["triceps","push","upper"],rest:"90s",howTo:["Hands shoulder-width.","Lower to chest, elbows tucked.","Focus on tricep lockout."],books:["Copy of OffSeason_2ndEdition_Final.pdf"],kw:["close","grip","bench"]},
  {id:"ohp",name:"DB Overhead Press",tags:["shoulders","push","upper"],rest:"90s",howTo:["Dumbbells at shoulder height.","Press overhead to full extension.","Lower under control."],books:["Copy of OffSeason_2ndEdition_Final.pdf"],kw:["overhead","press","shoulder"]},
  {id:"squat",name:"Back Squat",tags:["legs","strength","lower"],rest:"2-3 min",howTo:["Bar on upper traps, brace hard.","Sit below parallel.","Drive up through mid-foot."],books:["Copy of OffSeason_2ndEdition_Final.pdf","WrestlingEBook2_FINAL.compressed.pdf"],kw:["squat","legs","barbell"]},
  {id:"deadlift",name:"Conventional Deadlift",tags:["posterior","pull","lower"],rest:"2-3 min",howTo:["Bar over mid-foot, grip outside knees.","Push floor away, chest up.","Lock out hips — don't hyperextend."],books:["Copy of OffSeason_2ndEdition_Final.pdf","IN Season workouts.pdf"],kw:["deadlift","pull","hinge"]},
  {id:"rdl",name:"Romanian Deadlift",tags:["hamstrings","pull","lower"],rest:"90s",howTo:["Hinge at hips, slight knee bend.","Feel hamstring stretch.","Drive hips forward to stand."],books:["Copy of OffSeason_2ndEdition_Final.pdf"],kw:["romanian","deadlift","hamstring"]},
  {id:"row",name:"Barbell Row",tags:["back","pull","upper"],rest:"90s",howTo:["Stand with your feet shoulder-width apart.","Hinge forward at your hips at about a 45-degree angle, keeping your back straight and your core tight.","Grip the barbell (or dumbbells) slightly wider than shoulder-width.","Pull the weight up toward your lower ribs, driving your elbows back and squeezing your shoulder blades together.","Lower the weight slowly and under control back to the starting hanging position."],books:["Copy of OffSeason_2ndEdition_Final.pdf"],kw:["row","back","barbell"]},
  {id:"pullup",name:"Pull-Up",tags:["back","pull","upper"],rest:"90s",howTo:["Dead hang, palms away.","Pull chin over bar.","Lower with full control."],books:["WrestlingEBook2_FINAL.compressed.pdf"],kw:["pull","up","back","lat"]},
  {id:"face_pull",name:"Band Face Pull",tags:["shoulders","upper"],rest:"60s",howTo:["Attach a resistance band to a sturdy anchor point at face height.","Grab the ends of the band with both hands and step back until there is tension.","Pull the band apart and toward your face, driving your elbows back and rotating your hands upward so your knuckles point toward the ceiling.","Squeeze your upper back and shoulder blades together for 1 second, then slowly release."],books:["Copy of OffSeason_2ndEdition_Final.pdf"],kw:["face","pull","band"]},
  {id:"lunge",name:"Walking Lunges (DB)",tags:["legs","lower"],rest:"60s",howTo:["Stand tall holding dumbbells down at your sides.","Take a large step forward with one foot.","Drop your hips straight down until your front knee is at a 90-degree angle and your back knee is hovering just an inch above the floor.","Push forcefully off your front heel to bring your back foot forward, stepping right into the next lunge.","Keep your chest up and core engaged the whole time."],books:["Copy of OffSeason_2ndEdition_Final.pdf"],kw:["lunge","legs","dumbbell"]},
  {id:"bss",name:"Bulgarian Split Squat",tags:["legs","lower"],rest:"60s",howTo:["Rear foot on bench.","Lower until back knee near floor.","Drive up through front heel."],books:["Copy of OffSeason_2ndEdition_Final.pdf"],kw:["bulgarian","split","squat"]},
  {id:"pushup",name:"Push-Up",tags:["chest","bodyweight"],rest:"—",howTo:["Rigid plank, hands under shoulders.","Lower chest to floor.","Press to lockout."],books:["28DayPlan_FinalVersion.pdf"],kw:["pushup","chest"]},
  {id:"burpee",name:"Burpee",tags:["conditioning","bodyweight"],rest:"—",howTo:["Drop, kick back to plank.","Push-up, hop forward.","Explode up with jump."],books:["28DayPlan_FinalVersion.pdf"],kw:["burpee","conditioning"]},
  {id:"int800",name:"800m Repeats",tags:["running","speed"],rest:"90s walk",howTo:["Warm up 8-10 min.","Run each 800m at target split.","Walk 90-120s recovery."],books:["IN Season workouts.pdf"],kw:["800","interval","run"]},
  {id:"tempo",name:"Tempo Run",tags:["running","endurance"],rest:"—",howTo:["10-min easy warmup.","Hard sustainable pace.","5-min cooldown."],books:["IN Season workouts.pdf"],kw:["tempo","threshold","run"]},
  {id:"farmer",name:"Farmer Carry",tags:["grip","core"],rest:"60s",howTo:["Heavy DBs, stand tall.","Short controlled steps.","Maintain grip full distance."],books:["Copy of OffSeason_2ndEdition_Final.pdf"],kw:["farmer","carry","grip"]},
  {id:"plank",name:"Plank Hold",tags:["core","bodyweight"],rest:"30s",howTo:["Get onto the floor resting on your forearms and toes.","Your elbows should be directly underneath your shoulders.","Create a rigid, straight line from your head down to your heels.","Squeeze your glutes, thighs, and core tightly.","Do not let your hips sag toward the floor or pike up toward the ceiling.","Breathe steadily while you hold."],books:["28DayPlan_FinalVersion.pdf"],kw:["plank","core"]},
  {id:"air_squat",name:"Air Squat",tags:["legs","bodyweight"],rest:"—",howTo:["Stand with your feet slightly wider than shoulder-width apart, toes pointed slightly outward.","Keep your chest up and core tight.","Push your hips back and bend your knees to lower into a squat, as if sitting in a chair.","Try to get your hips below parallel with your knees.","Drive explosively through your whole foot to stand back up, squeezing your glutes at the top."],books:["28DayPlan_FinalVersion.pdf"],kw:["air","squat"]},
  {id:"shadow",name:"Burpee complexes",tags:["conditioning","bodyweight"],rest:"—",howTo:["Hands to floor, jump or step back to plank.","Add a push-up if you want more upper-body work.","Stand and hop — optional wide-foot 'sprawl' step instead of a jump."],books:["28DayPlan_FinalVersion.pdf"],kw:["burpee","conditioning","sprawl"]},
  {id:"dip",name:"Dip",tags:["chest","triceps","upper"],rest:"90s",howTo:["Support on bars, arms locked.","Lower until upper arms parallel.","Press to lockout."],books:["Copy of OffSeason_2ndEdition_Final.pdf"],kw:["dip","triceps"]},
  {id:"lat_raise",name:"Lateral Raise",tags:["shoulders","upper"],rest:"45s",howTo:["Light DBs at sides.","Raise to shoulder height.","Lower slowly."],books:["Copy of OffSeason_2ndEdition_Final.pdf"],kw:["lateral","raise","shoulder"]},
  {id:"kb_around",name:"KB Around the World",tags:["core","pilates","home"],rest:"30s",howTo:["Stand tall with your feet shoulder-width apart, holding a kettlebell (or dumbbell) at chest height.","Brace your core tight, keeping your ribs pulled down and your hips facing squarely forward.","Slowly circle the weight around your head and torso in one direction.","Keep the rest of your body completely still as the weight moves.","Switch directions after a set number of reps."],books:["28DayPlan_FinalVersion.pdf"],kw:["kettlebell","around the world","core"]},
  {id:"suitcase",name:"Suitcase Carry",tags:["core","obliques","home"],rest:"45s",howTo:["Stand perfectly tall holding a heavy dumbbell or kettlebell in one hand at your side, like a heavy suitcase.","Brace your core and avoid leaning away from or toward the weight—your shoulders should remain level.","Walk forward slowly with perfect posture.","Switch the weight to the other hand for the next set."],books:["28DayPlan_FinalVersion.pdf"],kw:["suitcase","carry","oblique"]},
  {id:"db_leg_raise",name:"DB Leg Raise",tags:["core","lower abs","home"],rest:"30s",howTo:["Lie on your back on a mat.","If you feel comfortable, hold a light dumbbell securely between your feet.","Press your lower back firmly into the floor—this is the most important part.","Keeping your legs straight (or slightly bent if needed), lift them straight up toward the ceiling.","Lower them slowly, only going as far down as you can without your lower back lifting off the mat."],books:["28DayPlan_FinalVersion.pdf"],kw:["leg raise","lower abs","dumbbell"]},
  {id:"toe_tap",name:"Toe Tap (Dead Bug)",tags:["core","postpartum","home"],rest:"30s",howTo:["Lie flat on your back and lift your legs so your knees are bent at a perfect 90-degree angle (like sitting in a chair in the air).","Reach your arms straight up.","Press your lower back flat against the floor.","Slowly lower one foot to tap your toes on the floor, keeping the knee bent.","Exhale and brace your core as you do this.","Bring the leg back up and switch to the other leg."],books:["28DayPlan_FinalVersion.pdf"],kw:["toe tap","dead bug","core"]},
  {id:"cross_press",name:"DB Cross Press",tags:["back","arms","hourglass"],rest:"45s",howTo:["Stand with a slight forward hinge at your hips, holding a light dumbbell in each hand in front of your body.","Keeping your shoulders pulled down and away from your ears, press one dumbbell diagonally upward and across your body.","Bring it back to the start with control, and then repeat on the other side."],books:["28DayPlan_FinalVersion.pdf"],kw:["cross press","dumbbell","back"]},
  {id:"chest_sweep",name:"Chest Sweep",tags:["arms","posture","pilates"],rest:"45s",howTo:["Stand or sit tall holding very light dumbbells.","Keep a soft bend in your elbows.","Starting with your arms down by your sides, sweep your arms upward and inward in a wide, controlled arc until the dumbbells meet in front of your chest.","Keep your ribcage pulled down and your neck long and relaxed.","Reverse the sweep slowly to return to the start."],books:["28DayPlan_FinalVersion.pdf"],kw:["chest sweep","arms","tone"]},
  {id:"champagne",name:"Champagne Pour",tags:["shoulders","arms","posture"],rest:"45s",howTo:["Stand tall holding a dumbbell in each hand in front of your chest, with your elbows bent at 90 degrees and palms facing each other.","Rotate your wrists and forearms outward, tipping the dumbbells forward as if you are pouring two glasses of champagne.","Pause at the end of the rotation, then slowly return to the starting position."],books:["28DayPlan_FinalVersion.pdf"],kw:["champagne pour","shoulders","arms"]},
  {id:"medball_circuit",name:"Medball Sculpt Circuit",tags:["conditioning","home","fullbody"],rest:"30s",howTo:["This is a continuous series of movements using a medicine ball.","Start with Medball Slams (lift the ball overhead and slam it into the ground, catching it on the bounce).","Move into a Squat-to-Press (hold the ball at your chest, squat down, and push the ball overhead as you stand).","Finish with Rotations (hold the ball in front of you and twist your torso side to side).","Move smoothly between exercises for a set time."],books:["28DayPlan_FinalVersion.pdf"],kw:["medicine ball","circuit","full body"]},
  {id:"pelvic_breath",name:"Pelvic Floor Breathing",tags:["pregnancy","postpartum","recovery"],rest:"30s",howTo:["Find a comfortable seated or lying position.","Take a deep inhale through your nose, feeling your ribcage expand out to the sides and back.","As you take a long, slow exhale through your mouth, gently lift and engage your pelvic floor (imagine trying to stop the flow of urine and hold in gas simultaneously).","Keep the contraction gentle and pain-free, then fully relax it on your next inhale."],books:["28DayPlan_FinalVersion.pdf"],kw:["pelvic floor","breathing","postpartum"]},
  {id:"hip_thrust",name:"DB/Band Hip Thrust",tags:["glutes","home","lower"],rest:"45s",howTo:["Sit on the floor with your upper back resting against the edge of a sturdy bench or sofa.","Place a dumbbell or resistance band across your hip crease (if using weight), and plant your feet firmly on the ground, shoulder-width apart.","Drive your hips up toward the ceiling by pushing through your heels.","At the top of the movement, your knees should be at a 90-degree angle and your body should form a straight line from your shoulders to your knees.","Squeeze your glutes hard at the top, then lower your hips back down with control."],books:["28DayPlan_FinalVersion.pdf"],kw:["hip thrust","glute bridge","glutes"]},
  {id:"fire_hydrant",name:"Fire Hydrant",tags:["glutes","home","medius"],rest:"30s",howTo:["Start on your hands and knees (all fours) with your hands directly under your shoulders and your knees under your hips.","Keep your spine in a neutral, flat position and brace your core.","Keeping your knee bent at a 90-degree angle, lift one leg out to the side as high as you comfortably can without twisting your torso or dropping your opposite hip.","Pause for a second at the top, then slowly lower your leg back to the starting position."],books:["28DayPlan_FinalVersion.pdf"],kw:["fire hydrant","glute medius"]},
  {id:"clamshell",name:"Banded Clamshell",tags:["glutes","home","medius"],rest:"30s",howTo:["Lie on your side with your legs stacked and your knees bent at about a 45-degree angle.","If you have a resistance band, place it just above your knees.","Rest your head on your lower arm.","Keep your feet touching each other and your hips facing completely forward.","Slowly open your top knee toward the ceiling, like a clamshell opening.","Squeeze your side glute at the top, then slowly close your legs with control."],books:["28DayPlan_FinalVersion.pdf"],kw:["clamshell","glute medius","band"]},
  {id:"donkey_kick",name:"Donkey Kick",tags:["glutes","home"],rest:"30s",howTo:["Begin on all fours with your hands under your shoulders and knees under your hips.","Brace your core to keep your lower back from arching.","Keeping your right knee bent at a 90-degree angle and your foot flexed, drive your right heel up and back toward the ceiling.","Squeeze your glute at the top of the movement, ensuring your lower back stays completely still.","Lower the knee back down slowly."],books:["28DayPlan_FinalVersion.pdf"],kw:["donkey kick","glute"]},
  {id:"side_leg_raise",name:"Side-Lying Leg Raise",tags:["glutes","hips","home"],rest:"30s",howTo:["Lie on your side with your bottom leg slightly bent for stability and your top leg perfectly straight.","Rest your head on your arm.","Slightly angle the toes of your top foot downward toward the floor.","Slowly raise the top leg straight up into the air, focusing on using the muscles on the outer side of your hip and glute.","Lower the leg slowly and controlled back to the starting position."],books:["28DayPlan_FinalVersion.pdf"],kw:["side leg raise","hip dip","glute medius"]}
];
export function exById(id){return EX.find(e=>e.id===id)}
export const EX_MEDIA={
  bench:{video:"https://www.youtube.com/embed/rT7DgCr-3pg",grow:["chest","triceps","frontShoulders"],burn:["upperBody"]},
  incline_db:{video:"https://www.youtube.com/embed/8iPEnn-ltC8",grow:["chest","frontShoulders","triceps"],burn:["upperBody"]},
  cgbench:{video:"https://www.youtube.com/embed/nEF0bv2FW94",grow:["triceps","chest"],burn:["upperBody"]},
  ohp:{video:"https://www.youtube.com/embed/qEwKCR5JCog",grow:["frontShoulders","triceps"],burn:["upperBody"]},
  squat:{video:"https://www.youtube.com/embed/ultWZbUMPL8",grow:["quads","glutes","core"],burn:["lowerBody"]},
  deadlift:{video:"https://www.youtube.com/embed/op9kVnSso6Q",grow:["hamstrings","glutes","back","core"],burn:["fullBody"]},
  rdl:{video:"https://www.youtube.com/embed/jEy_czb3RKA",grow:["hamstrings","glutes","back"],burn:["lowerBody"]},
  row:{video:"https://www.youtube.com/shorts/HamNqVyElPc",grow:["back","biceps"],burn:["upperBody"]},
  pullup:{video:"https://www.youtube.com/embed/eGo4IYlbE5g",grow:["back","biceps"],burn:["upperBody"]},
  face_pull:{video:"https://www.youtube.com/watch?v=jQ1O7NeLmck",grow:["rearShoulders","back"],burn:["upperBody"]},
  lunge:{video:"https://www.youtube.com/watch?v=T7h-cdaAE74",grow:["quads","glutes"],burn:["lowerBody"]},
  bss:{video:"https://www.youtube.com/embed/2C-uNgKwPLE",grow:["quads","glutes"],burn:["lowerBody"]},
  pushup:{video:"https://www.youtube.com/embed/IODxDxX7oi4",grow:["chest","triceps","core"],burn:["upperBody"]},
  burpee:{video:"https://www.youtube.com/embed/dZgVxmf6jkA",grow:["legs","core","shoulders"],burn:["fullBody"]},
  int800:{video:"https://www.youtube.com/embed/5I4xD4-HRFA",grow:["legs","core"],burn:["fullBody","cardio"]},
  tempo:{video:"https://www.youtube.com/embed/5I4xD4-HRFA",grow:["legs","core"],burn:["fullBody","cardio"]},
  farmer:{video:"https://www.youtube.com/embed/rt17lmnaLSM",grow:["core","back","forearms"],burn:["fullBody"]},
  plank:{video:"https://www.youtube.com/watch?v=nCqbUKl3XvU",grow:["core"],burn:["core"]},
  air_squat:{video:"https://www.youtube.com/watch?v=R0vJBTrzLac",grow:["quads","glutes"],burn:["lowerBody"]},
  shadow:{video:"https://www.youtube.com/embed/dZgVxmf6jkA",grow:["legs","core","shoulders"],burn:["fullBody","cardio"]},
  dip:{video:"https://www.youtube.com/embed/2z8JmcrW-As",grow:["triceps","chest"],burn:["upperBody"]},
  lat_raise:{video:"https://www.youtube.com/embed/3VcKaXpzqRo",grow:["sideShoulders"],burn:["upperBody"]},
  kb_around:{video:"https://www.youtube.com/shorts/lqupOdAp2i0",grow:["core","shoulders"],burn:["core"]},
  suitcase:{video:"https://www.youtube.com/watch?v=taFIJ3dbS28",grow:["core","forearms"],burn:["fullBody"]},
  db_leg_raise:{video:"https://www.youtube.com/watch?v=7Za5EIYSGDU",grow:["core"],burn:["core"]},
  toe_tap:{video:"https://www.youtube.com/shorts/Aoipu_fl3HA",grow:["core"],burn:["core"]},
  cross_press:{video:"https://www.youtube.com/watch?v=1ECTMQhPovU",grow:["back","rearShoulders"],burn:["upperBody"]},
  chest_sweep:{video:"https://www.youtube.com/watch?v=3zRNKl1hJjw",grow:["frontShoulders","chest"],burn:["upperBody"]},
  champagne:{video:"https://www.youtube.com/watch?v=oBXsluXGC6Y",grow:["rearShoulders","sideShoulders"],burn:["upperBody"]},
  medball_circuit:{video:"https://www.youtube.com/shorts/1CUdNDS-Qfg",grow:["legs","core","shoulders"],burn:["fullBody","cardio"]},
  pelvic_breath:{video:"https://www.youtube.com/shorts/lkL49txMNfQ",grow:["core"],burn:["core"]},
  hip_thrust:{video:"https://www.youtube.com/watch?v=Zp3mZV6Plyg",grow:["glutes","hamstrings"],burn:["lowerBody"]},
  fire_hydrant:{video:"https://www.youtube.com/watch?v=ng1P4Q4l2M8",grow:["glutes","hips"],burn:["lowerBody"]},
  clamshell:{video:"https://www.youtube.com/watch?v=t0ASA5CxgKI",grow:["glutes","hips"],burn:["lowerBody"]},
  donkey_kick:{video:"https://www.youtube.com/watch?v=OZH0-OB_sm0",grow:["glutes"],burn:["lowerBody"]},
  side_leg_raise:{video:"https://www.youtube.com/watch?v=wJo8inKVKus",grow:["glutes","hips"],burn:["lowerBody"]}
};
export const EX_MEDIA_FEMALE={
  bench:{video:"https://www.youtube.com/embed/4Y2ZdHCOXok"},
  incline_db:{video:"https://www.youtube.com/embed/8iPEnn-ltC8"},
  cgbench:{video:"https://www.youtube.com/embed/nEF0bv2FW94"},
  ohp:{video:"https://www.youtube.com/embed/qEwKCR5JCog"},
  squat:{video:"https://www.youtube.com/embed/Dy28eq2PjcM"},
  deadlift:{video:"https://www.youtube.com/embed/ytGaGIn3SjE"},
  rdl:{video:"https://www.youtube.com/embed/jEy_czb3RKA"},
  row:{video:"https://www.youtube.com/shorts/HamNqVyElPc"},
  pullup:{video:"https://www.youtube.com/embed/eGo4IYlbE5g"},
  face_pull:{video:"https://www.youtube.com/watch?v=jQ1O7NeLmck"},
  lunge:{video:"https://www.youtube.com/watch?v=T7h-cdaAE74"},
  bss:{video:"https://www.youtube.com/embed/2C-uNgKwPLE"},
  pushup:{video:"https://www.youtube.com/embed/IODxDxX7oi4"},
  burpee:{video:"https://www.youtube.com/embed/dZgVxmf6jkA"},
  int800:{video:"https://www.youtube.com/embed/5I4xD4-HRFA"},
  tempo:{video:"https://www.youtube.com/embed/5I4xD4-HRFA"},
  farmer:{video:"https://www.youtube.com/embed/rt17lmnaLSM"},
  plank:{video:"https://www.youtube.com/watch?v=nCqbUKl3XvU"},
  air_squat:{video:"https://www.youtube.com/watch?v=R0vJBTrzLac"},
  shadow:{video:"https://www.youtube.com/embed/dZgVxmf6jkA"},
  dip:{video:"https://www.youtube.com/embed/2z8JmcrW-As"},
  lat_raise:{video:"https://www.youtube.com/embed/3VcKaXpzqRo"},
  kb_around:{video:"https://www.youtube.com/shorts/lqupOdAp2i0"},
  suitcase:{video:"https://www.youtube.com/watch?v=taFIJ3dbS28"},
  db_leg_raise:{video:"https://www.youtube.com/watch?v=7Za5EIYSGDU"},
  toe_tap:{video:"https://www.youtube.com/shorts/Aoipu_fl3HA"},
  cross_press:{video:"https://www.youtube.com/watch?v=1ECTMQhPovU"},
  chest_sweep:{video:"https://www.youtube.com/watch?v=3zRNKl1hJjw"},
  champagne:{video:"https://www.youtube.com/watch?v=oBXsluXGC6Y"},
  medball_circuit:{video:"https://www.youtube.com/shorts/1CUdNDS-Qfg"},
  pelvic_breath:{video:"https://www.youtube.com/shorts/lkL49txMNfQ"},
  hip_thrust:{video:"https://www.youtube.com/watch?v=Zp3mZV6Plyg"},
  fire_hydrant:{video:"https://www.youtube.com/watch?v=ng1P4Q4l2M8"},
  clamshell:{video:"https://www.youtube.com/watch?v=t0ASA5CxgKI"},
  donkey_kick:{video:"https://www.youtube.com/watch?v=OZH0-OB_sm0"},
  side_leg_raise:{video:"https://www.youtube.com/watch?v=wJo8inKVKus"}
};
/** Optional ~2 min demo URLs (women-led); primary embed stays in EX_MEDIA / EX_MEDIA_FEMALE. */
export const EX_QUICK_DEMO_VIDEO={
  hip_thrust:"https://www.youtube.com/watch?v=_i6qpcI1Nw4",
  fire_hydrant:"https://www.youtube.com/watch?v=3UvmdA0bJ-w",
  clamshell:"https://www.youtube.com/watch?v=f-COgi-oVKY",
  donkey_kick:"https://www.youtube.com/watch?v=ArQnqLP-6BU",
  side_leg_raise:"https://www.youtube.com/watch?v=TdfRsUbODlM",
  row:"https://www.youtube.com/watch?v=dpYI8K6e-jE",
  cross_press:"https://www.youtube.com/watch?v=BGlB8hN-4CI",
  face_pull:"https://www.youtube.com/watch?v=FTA-s2df6M4",
  chest_sweep:"https://www.youtube.com/watch?v=wx6PVXOiON0",
  champagne:"https://www.youtube.com/watch?v=OlGEtnVqsYI",
  kb_around:"https://www.youtube.com/watch?v=XJO3g_ilkvs",
  suitcase:"https://www.youtube.com/watch?v=ZLEcO2bf1JA",
  db_leg_raise:"https://www.youtube.com/watch?v=B3WKx-zaWg8",
  toe_tap:"https://www.youtube.com/watch?v=htfn3L8Efw8",
  plank:"https://www.youtube.com/watch?v=UQ78pw0WNZI",
  medball_circuit:"https://www.youtube.com/watch?v=mhNgJlFNzD0",
  air_squat:"https://www.youtube.com/watch?v=dVjfUlXK93k",
  pelvic_breath:"https://www.youtube.com/watch?v=nmUr_pA4BCQ",
  lunge:"https://www.youtube.com/watch?v=2ea3_b9rFdM"
};
export const EX_MUSCLE_IDS={
  bench:{primary:["pectoralis_major_l","pectoralis_major_r"],secondary:["triceps_brachii_caput_longum_l","triceps_brachii_caput_longum_r"],tertiary:["anterior_deltoid_l","anterior_deltoid_r"],burn:["rectus_abdominis_1","external_oblique_1_l","external_oblique_1_r"]},
  incline_db:{primary:["pectoralis_major_l","pectoralis_major_r"],secondary:["anterior_deltoid_l","anterior_deltoid_r"],tertiary:["triceps_brachii_caput_longum_l","triceps_brachii_caput_longum_r"],burn:["rectus_abdominis_1"]},
  cgbench:{primary:["triceps_brachii_caput_laterale_l","triceps_brachii_caput_laterale_r","triceps_brachii_caput_longum_l","triceps_brachii_caput_longum_r"],secondary:["pectoralis_major_l","pectoralis_major_r"],tertiary:["anterior_deltoid_l","anterior_deltoid_r"],burn:["rectus_abdominis_1"]},
  ohp:{primary:["anterior_deltoid_l","anterior_deltoid_r"],secondary:["lateral_deltoid_l","lateral_deltoid_r","triceps_brachii_caput_longum_l","triceps_brachii_caput_longum_r"],tertiary:["external_oblique_1_l","external_oblique_1_r"],burn:["external_oblique_1_l","external_oblique_1_r"]},
  squat:{primary:["rectus_femoris_l","rectus_femoris_r","vastus_lateralis_l","vastus_lateralis_r","vastus_medialis_l","vastus_medialis_r"],secondary:["gluteus_maximus_l","gluteus_maximus_r"],tertiary:["rectus_abdominis_1","external_oblique_1_l","external_oblique_1_r"],burn:["rectus_abdominis_1","external_oblique_1_l","external_oblique_1_r"]},
  deadlift:{primary:["gluteus_maximus_l","gluteus_maximus_r","biceps_femoris_l","biceps_femoris_r","semitendinosus_l","semitendinosus_r"],secondary:["latissimus_dorsi_l","latissimus_dorsi_r","trapezius_middle_l","trapezius_middle_r"],tertiary:["rectus_abdominis_1","external_oblique_1_l","external_oblique_1_r"],burn:["rectus_abdominis_1","external_oblique_1_l","external_oblique_1_r"]},
  rdl:{primary:["biceps_femoris_l","biceps_femoris_r","semitendinosus_l","semitendinosus_r"],secondary:["gluteus_maximus_l","gluteus_maximus_r"],tertiary:["rectus_abdominis_1"],burn:["rectus_abdominis_1"]},
  row:{primary:["latissimus_dorsi_l","latissimus_dorsi_r"],secondary:["infraspinatus_l","infraspinatus_r","trapezius_middle_l","trapezius_middle_r"],tertiary:["biceps_brachii_caput_longum_l","biceps_brachii_caput_longum_r"],burn:["external_oblique_1_l","external_oblique_1_r"]},
  pullup:{primary:["latissimus_dorsi_l","latissimus_dorsi_r"],secondary:["biceps_brachii_caput_longum_l","biceps_brachii_caput_longum_r"],tertiary:["trapezius_upper_l","trapezius_upper_r"],burn:["rectus_abdominis_1"]},
  face_pull:{primary:["posterior_deltoid_l","posterior_deltoid_r"],secondary:["trapezius_middle_l","trapezius_middle_r","infraspinatus_l","infraspinatus_r"],tertiary:[],burn:["trapezius_middle_l","trapezius_middle_r"]},
  lunge:{primary:["rectus_femoris_l","rectus_femoris_r","vastus_medialis_l","vastus_medialis_r"],secondary:["gluteus_maximus_l","gluteus_maximus_r"],tertiary:["adductor_longus_l","adductor_longus_r"],burn:["rectus_femoris_l","rectus_femoris_r"]},
  bss:{primary:["rectus_femoris_l","rectus_femoris_r","vastus_lateralis_l","vastus_lateralis_r"],secondary:["gluteus_maximus_l","gluteus_maximus_r"],tertiary:["external_oblique_1_l","external_oblique_1_r"],burn:["rectus_femoris_l","rectus_femoris_r"]},
  pushup:{primary:["pectoralis_major_l","pectoralis_major_r"],secondary:["triceps_brachii_caput_longum_l","triceps_brachii_caput_longum_r"],tertiary:["anterior_deltoid_l","anterior_deltoid_r","rectus_abdominis_1"],burn:["rectus_abdominis_1"]},
  burpee:{primary:["rectus_femoris_l","rectus_femoris_r","pectoralis_major_l","pectoralis_major_r"],secondary:["anterior_deltoid_l","anterior_deltoid_r"],tertiary:["rectus_abdominis_1"],burn:["rectus_femoris_l","rectus_femoris_r","rectus_abdominis_1"]},
  int800:{primary:["rectus_femoris_l","rectus_femoris_r","vastus_lateralis_l","vastus_lateralis_r"],secondary:["gastrocnemius_l","gastrocnemius_r"],tertiary:["external_oblique_1_l","external_oblique_1_r"],burn:["rectus_femoris_l","rectus_femoris_r","gastrocnemius_l","gastrocnemius_r"]},
  tempo:{primary:["rectus_femoris_l","rectus_femoris_r"],secondary:["gastrocnemius_l","gastrocnemius_r"],tertiary:["external_oblique_1_l","external_oblique_1_r"],burn:["rectus_femoris_l","rectus_femoris_r","gastrocnemius_l","gastrocnemius_r"]},
  farmer:{primary:["trapezius_upper_l","trapezius_upper_r","brachioradialis_l","brachioradialis_r"],secondary:["external_oblique_1_l","external_oblique_1_r"],tertiary:["latissimus_dorsi_l","latissimus_dorsi_r"],burn:["external_oblique_1_l","external_oblique_1_r"]},
  plank:{primary:["rectus_abdominis_1","external_oblique_1_l","external_oblique_1_r"],secondary:[],tertiary:[],burn:["rectus_abdominis_1","external_oblique_1_l","external_oblique_1_r"]},
  air_squat:{primary:["rectus_femoris_l","rectus_femoris_r"],secondary:["gluteus_maximus_l","gluteus_maximus_r"],tertiary:["gastrocnemius_l","gastrocnemius_r"],burn:["rectus_femoris_l","rectus_femoris_r"]},
  shadow:{primary:["rectus_femoris_l","rectus_femoris_r","pectoralis_major_l","pectoralis_major_r"],secondary:["anterior_deltoid_l","anterior_deltoid_r"],tertiary:["rectus_abdominis_1"],burn:["rectus_femoris_l","rectus_femoris_r","rectus_abdominis_1"]},
  dip:{primary:["triceps_brachii_caput_laterale_l","triceps_brachii_caput_laterale_r"],secondary:["pectoralis_major_l","pectoralis_major_r"],tertiary:["anterior_deltoid_l","anterior_deltoid_r"],burn:["triceps_brachii_caput_laterale_l","triceps_brachii_caput_laterale_r"]},
  lat_raise:{primary:["lateral_deltoid_l","lateral_deltoid_r"],secondary:[],tertiary:[],burn:["lateral_deltoid_l","lateral_deltoid_r"]},
  kb_around:{primary:["external_oblique_1_l","external_oblique_1_r"],secondary:["anterior_deltoid_l","anterior_deltoid_r"],tertiary:["rectus_abdominis_1"],burn:["external_oblique_1_l","external_oblique_1_r"]},
  suitcase:{primary:["external_oblique_1_l","external_oblique_1_r"],secondary:["brachioradialis_l","brachioradialis_r"],tertiary:["rectus_abdominis_1"],burn:["external_oblique_1_l","external_oblique_1_r"]},
  db_leg_raise:{primary:["rectus_abdominis_1"],secondary:["external_oblique_1_l","external_oblique_1_r"],tertiary:[],burn:["rectus_abdominis_1"]},
  toe_tap:{primary:["rectus_abdominis_1"],secondary:["external_oblique_1_l","external_oblique_1_r"],tertiary:["transverse_abdominis"],burn:["rectus_abdominis_1"]},
  cross_press:{primary:["latissimus_dorsi_l","latissimus_dorsi_r"],secondary:["posterior_deltoid_l","posterior_deltoid_r"],tertiary:["biceps_brachii_caput_longum_l","biceps_brachii_caput_longum_r"],burn:["external_oblique_1_l","external_oblique_1_r"]},
  chest_sweep:{primary:["anterior_deltoid_l","anterior_deltoid_r"],secondary:["pectoralis_major_l","pectoralis_major_r"],tertiary:["biceps_brachii_caput_longum_l","biceps_brachii_caput_longum_r"],burn:["anterior_deltoid_l","anterior_deltoid_r"]},
  champagne:{primary:["posterior_deltoid_l","posterior_deltoid_r"],secondary:["lateral_deltoid_l","lateral_deltoid_r"],tertiary:["infraspinatus_l","infraspinatus_r"],burn:["posterior_deltoid_l","posterior_deltoid_r"]},
  medball_circuit:{primary:["rectus_femoris_l","rectus_femoris_r","external_oblique_1_l","external_oblique_1_r"],secondary:["anterior_deltoid_l","anterior_deltoid_r"],tertiary:["gluteus_maximus_l","gluteus_maximus_r"],burn:["rectus_femoris_l","rectus_femoris_r","external_oblique_1_l","external_oblique_1_r"]},
  pelvic_breath:{primary:["rectus_abdominis_1"],secondary:["external_oblique_1_l","external_oblique_1_r"],tertiary:[],burn:["rectus_abdominis_1"]},
  hip_thrust:{primary:["gluteus_maximus_l","gluteus_maximus_r"],secondary:["biceps_femoris_l","biceps_femoris_r"],tertiary:["rectus_abdominis_1"],burn:["gluteus_maximus_l","gluteus_maximus_r"]},
  fire_hydrant:{primary:["gluteus_maximus_l","gluteus_maximus_r"],secondary:["gluteus_medius_l","gluteus_medius_r"],tertiary:["external_oblique_1_l","external_oblique_1_r"],burn:["gluteus_maximus_l","gluteus_maximus_r"]},
  clamshell:{primary:["gluteus_medius_l","gluteus_medius_r"],secondary:["gluteus_maximus_l","gluteus_maximus_r"],tertiary:[],burn:["gluteus_medius_l","gluteus_medius_r"]},
  donkey_kick:{primary:["gluteus_maximus_l","gluteus_maximus_r"],secondary:["biceps_femoris_l","biceps_femoris_r"],tertiary:["external_oblique_1_l","external_oblique_1_r"],burn:["gluteus_maximus_l","gluteus_maximus_r"]},
  side_leg_raise:{primary:["gluteus_medius_l","gluteus_medius_r"],secondary:["tensor_fasciae_latae_l","tensor_fasciae_latae_r"],tertiary:["external_oblique_1_l","external_oblique_1_r"],burn:["gluteus_medius_l","gluteus_medius_r"]}
};

